name: Automatic deployment after pushing to main

on:
  push:
    branches:
      [ main ]

jobs:
  push_to_dockerhub:
    runs-on: ubuntu-20.04
    env:
      REPOSITORY_PREFIX: "${{ secrets.DOCKERHUB_USER }}"
      PATHS: customers-service vets-service visits-service
    steps: 
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Login into Docker Hub account
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build images
      working-directory: ./spring-petclinic-cloud
      run: for path in ${{ env.PATHS }}; do cd "spring-petclinic-${path}" && mvn spring-boot:build-image -Pk8s -DREPOSITORY_PREFIX=${{ env.REPOSITORY_PREFIX }} && cd ..; done
    - name: Push images
      run: for path in ${{ env.PATHS }}; do docker push "${{ env.REPOSITORY_PREFIX }}/spring-petclinic-cloud-${p}:${{ env.TAG }}"; done
  deploy:
    needs: [ push_to_dockerhub ]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GKE_SERVICE_ACCESS_KEY }}
    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GKE_REGION }}
    - name: Deploy images
      working-directory: ./spring-petclinic-cloud
      run: chmod +x scripts/deployToKubernetes.sh && ./scripts/deployToKubernetes.sh
